services:
  http:
    build:
      context: ../../..
      dockerfile: http/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres-avito-informer
    ports:
      - "${EXTERNAL_HTTP_PORT}:${HTTP_PORT}"
    networks:
      - avito-informer-net

  collector:
    build:
      context: ../../..
      dockerfile: collector/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres-avito-informer
    networks:
      - avito-informer-net
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1G

  notification:
    build:
      context: ../../..
      dockerfile: notification/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres-avito-informer
    networks:
      - avito-informer-net

  postgres-avito-informer:
    image: postgres:17.0-alpine3.20
    container_name: postgres-avito-informer
    hostname: postgres_avito_informer
    env_file:
      - .env
    volumes:
      - postgres_avito_informer_data:/var/lib/postgresql/data
    ports:
      - "${EXTERNAL_POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s  # Интервал между проверками — каждые 10 секунд
      timeout: 5s    # Время ожидания ответа от проверки
      retries: 5     # После 5 неудачных попыток подряд контейнер считается "unhealthy"
    restart: unless-stopped
    networks:
      - avito-informer-net

volumes:
  postgres_avito_informer_data:

networks:
  avito-informer-net:
    name: avito-informer-net
    external: false
